# Use official Node.js image
FROM node:23-alpine

# Set the working directory inside the container
WORKDIR /app

# Install app dependencies using npm
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# RUN npm install to install dependencies
# If you are building your code for production use the next line instead of previous line
RUN npm install --omit=dev

# Copy the project files
COPY . .

# Expose application port
EXPOSE 8080

# Command to start the app
CMD [ "node", "app.js" ]
